WIP: Implement offsetof as builtin
ForNeVeR/Cesium pull request #379
Opened 2023-05-01 19:18 UTC by zawodskoj

Replacement for #374 - I decided to make it different PR as the implementation differs largely.

This implementation introduces builtin to obtain ptr to dirty instance of arbitrary struct.
This allows to write macro appropriate to offsetof features that previous implementation was unable to cover.
For example, `offsetof(foo, bar.baz)` now works.

This PR also uncovers discrepancy between default .net struct layout and msvc struct layout - I was forced to use Sequential struct layout for tests to match msvc offsets (related to #355?)

Do not merge: this PR depends on #377 and should be rebased before
Also there's a lot of testing code and dirty places, which requires some tidying.

2023-05-03 20:35 UTC, ForNeVeR commented
> Do not merge: this PR depends on https://github.com/ForNeVeR/Cesium/pull/377 and should be rebased before

In such cases, usually it's better to convert a PR to a draft, for ease of tracking.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/92793/236043561-d52428d1-507e-41fb-bdd1-b6fc39e48c1d.png">

2023-05-04 06:33 UTC, zawodskoj commented
Hah, in Gitlab there's automatic marking of WIP MRs

ср, 3 мая 2023 г., 23:35 Friedrich von Never ***@***.***>:

> Do not merge: this PR depends on #377
> <https://github.com/ForNeVeR/Cesium/pull/377> and should be rebased before
>
> In such cases, usually it's better to convert a PR to a draft, for ease of
> tracking.
> [image: image]
> <https://user-images.githubusercontent.com/92793/236043561-d52428d1-507e-41fb-bdd1-b6fc39e48c1d.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ForNeVeR/Cesium/pull/379#issuecomment-1533702432>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB7JUMVQCWUYW4P4WI7QBSLXEK6SPANCNFSM6AAAAAAXSCX24Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-04 06:38 UTC, kant2002 commented
If you make changes to codegen and that results in broken unit tests, you should run `.\scripts\approve-all.ps1` so you can update baseline. Also that way you can validate that your changes is what you expect.

2023-05-08 22:09 UTC, zawodskoj commented
I've rebased this branch and "fixed" all of the tests. There's now an identical layout for all of architectures - forced sequential with 4-byte packing. This change allows to pass a single test which does not actually need to pass anywhere - relying on specific field offsets is UB. I don't know how to test this feature properly, unless we're support specific alignment attributes like `__attribute__ ((aligned (4)))`

I can replace offsetof test with a reasonable check that the pointer is inside adequate bounds, so this PR will not need messing around default pointer alignment.

2023-05-08 22:50 UTC, zawodskoj commented
I'm unable to write tests in Cesium.CodeGen.Tests due to lack of preprocessor support in tests

2023-05-09 19:16 UTC, ForNeVeR commented
Why don't you use `__builtin_offsetof_instance` in those tests? It seems appropriate.

2023-05-09 19:54 UTC, zawodskoj commented
It should work this way, but I think tests should support preprocessor anyway

2023-05-09 20:02 UTC, ForNeVeR commented
I believe that the codegen tests should mostly test codegen, and could ignore preprocessor.

There are also integration tests that test everything in complex; I also agree that it would be beneficial to add such tests for this feature as well. Take a look at how `Cesium.IntegrationTests` are structured.

2023-05-09 20:08 UTC, zawodskoj commented
I've added some codegen tests
There's already a test on offsetof in IntegrationTests

2023-05-09 20:55 UTC, zawodskoj commented
Rebased - commits are cleansed from testing crap

2023-05-12 19:26 UTC, ForNeVeR requested changes
This is great! I've left some notes and will work on them myself in a moment.

2023-05-12 19:26 UTC, ForNeVeR commented on Cesium.CodeGen.Tests/CodeGenPointersTests.cs
> +    // Tests below rely on preprocessor, which is not supported in tests now
Note for self: let's open an issue and figure out what to do with these tests.

2023-05-12 19:26 UTC, ForNeVeR commented on Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
> +        if (_function.Identifier == "__builtin_offsetof_instance")
Another note for self: let's open an issue on extracting the builtin list to some special place.

2023-05-12 19:26 UTC, ForNeVeR commented on Cesium.CodeGen/Ir/Expressions/InstanceForOffsetOfExpression.cs
> +internal class InstanceForOffsetOfExpression : IExpression, IValueExpression, IAddressableValue
```suggestion
/// <summary>Takes an address of an instance of the passed type as part of the offsetof expression.</summary>
internal class InstanceForOffsetOfExpression : IExpression, IValueExpression, IAddressableValue
```

2023-05-12 19:26 UTC, ForNeVeR commented on Cesium.CodeGen/Ir/Expressions/FunctionCallExpression.cs
> +        if (_function.Identifier == "__builtin_offsetof_instance")
Let's document this somewhere.

2023-05-12 19:42 UTC, ForNeVeR approved these changes
Thanks!

2023-05-12 19:42 UTC, merged