Add function for testing that type can be resolved
ForNeVeR/Cesium pull request #382
Opened 2023-05-03 04:55 UTC by kant2002

2023-05-04 02:03 UTC, kant2002 commented
In case when unresolved type somewhere deep inside the struct we can known what type trigger cascading failures. That’s how original logic works. 

Reporting is still awful but I do not see how can I make proper infrastructure for it.

2023-05-06 17:10 UTC, ForNeVeR requested changes
I apporve this in principle, but could you please add a couple of tests for this new logic?

2023-05-06 17:10 UTC, ForNeVeR commented on Cesium.CodeGen/Contexts/TranslationUnitContext.cs
> +            bool isFunctionResolved = true;
Ok, so there are a lot of warnings on that the variable is unused. Could you remove it then?

2024-01-23 12:51 UTC, ForNeVeR commented
@kant2002 do you still think we need this? Sadly, I can't remember what the original intent was.

2024-01-23 13:33 UTC, closed without merging