Add tests for compilation of two source files with identical types.
ForNeVeR/Cesium pull request #482
Opened 2023-11-18 17:58 UTC by kant2002

2023-11-18 18:00 UTC, kant2002 commented
Probably depends on #481 since I was testing from that branch.

2023-11-23 21:37 UTC, ForNeVeR requested changes

2023-11-23 21:37 UTC, ForNeVeR commented on Cesium.CodeGen/Ir/Types/EnumType.cs
> +internal sealed class EnumType : IType, IEquatable<EnumType>
The compiler warnings here are correct, let's implement `GetHashCode` as well 😅

2023-11-23 21:37 UTC, ForNeVeR commented on Cesium.CodeGen/Ir/Types/StructType.cs
> +internal sealed class StructType : IGeneratedType, IEquatable<StructType>
Let's implement `GetHashCode` here, too.

2023-11-24 22:15 UTC, ForNeVeR approved these changes
Thanks!

2023-11-24 22:16 UTC, merged