Add #pragma pinvoke
ForNeVeR/Cesium pull request #550
Opened 2024-02-28 11:51 UTC by BadRyuner

Yes, this is not a good implementation of "#pragma pinvoke"...
Some methods I didn't name correctly, hope for some help with that!

But it's working just fine.

2024-02-28 12:07 UTC, BadRyuner commented
Need a good example of a pinvoke function call that is on all three platforms in the same library... On Windows "puts" function in mscvrt, on Linux "puts" function in libc...

2024-02-28 13:31 UTC, BadRyuner commented
Well, the tests passed.

2024-03-01 22:51 UTC, ForNeVeR requested changes
Great work! I've left some comments and ready to discuss minor issues.

2024-03-01 22:51 UTC, ForNeVeR commented on Cesium.CodeGen/Contexts/GlobalConstructorScope.cs
> +        return default;
Would this work?
```suggestion
        return _specialEffects.OfType<T>().FirstOrDefault();
```

2024-03-01 22:51 UTC, ForNeVeR commented on Cesium.CodeGen/Contexts/IDeclarationScope.cs
> +    void PushSpecialEffect(object declaration);
Please add a comment indicating our pragma as an example of this "special effect", for future readers.

2024-03-01 22:51 UTC, ForNeVeR commented on Cesium.CodeGen/Contexts/Meta/FunctionInfo.cs
> +    public string? DllImportNameStrip { get; set; }
Let's add documentation referencing `PInvokeDefinition.Prefix`, for the reader to get why are there two properties.

2024-03-01 22:51 UTC, ForNeVeR commented on Cesium.Preprocessor/CPreprocessor.cs
> +        var tokenizer = new CPreprocessorLexer("c:/null.c", code);
Let's either mark this as a `null` path (making the parameter nullable), or use some more specific name, like `<null>` or something.

2024-03-02 04:58 UTC, BadRyuner commented on Cesium.CodeGen.Tests/CodeGenPinvokeTests.cs
> +    }
This is from another test: [Cesium.Parsers.Tests->PreprocessorTests](https://github.com/ForNeVeR/Cesium/blob/63bd762e43f52dfd6cfb4ed1478fe190f84cd1fc/Cesium.Parser.Tests/PreprocessorTests/PreprocessorTests.cs#L26)
They don't overlap

2024-03-02 23:47 UTC, ForNeVeR approved these changes
Thanks!

2024-03-02 23:48 UTC, merged