Add support for implicit marshalling of the eq types
ForNeVeR/Cesium pull request #644
Opened 2024-09-06 09:40 UTC by kant2002

Also MSVC does not have support for strndup which is C23

2024-09-10 06:51 UTC, ForNeVeR requested changes

2024-09-10 06:51 UTC, ForNeVeR commented on Cesium.Runtime/StringFunctions.cs
> +        return dest;
I think this misses the null terminator. Please note this wording from the standard:
> If the array pointed to by `s` does not contain a null within the first size
characters, a null is appended to the copy of the array.

Meaning the result should always be null-terminated, regardless of `src[count]` being a null byte or not.

2024-09-10 06:52 UTC, ForNeVeR commented
I have to say: I am quite confused about all this `RESOLUTION_CESIUM` business, but let's make this a topic of a new issue, after we finish with this PR.

2024-09-10 07:26 UTC, kant2002 commented
Re: `RESOLUTION_CESIUM`. I almost manage to make it work, except it fails during runtime, since Cesium.Runtime cannot be resolved. I did not pursue investigation, current way of things was present originally. Need time to investigate and fix properly, maybe something simple.

2024-09-14 11:59 UTC, ForNeVeR approved these changes

2024-09-14 11:59 UTC, ForNeVeR commented
Thanks!

2024-09-14 11:59 UTC, merged